### ISSUE TITLE
proposal: integrate `serinus_cors`, `serinus_rate_limiter`, `serinus_config` and `serinus_serve_static` in the core package

### ISSUE THREAD

**Issue by mjablecnik** [francescovallone/serinus#78]
**Description**

Hello, I have a question about these Serinus packages:
- cors
- rate_limiter
- serinus_config
- serve_static

These packages are quite small and important in every normal web project. Why must be in some separate package instead of main serinus core package? 
Including these packages into core could prevent of existing many small packages and long project setup I think..

**Comment by francescovallone** [comment]
Hello, thank you for your question.

Yes, they are very important in every project for sure, but the idea behind Serinus is to allow the user to decide which package to use without forcing the use of a specific implementation. You could definitely think about putting them inside the core and if it's OK with you I would turn this issue into a proposal to talk about it in a more technical POV.

**Comment by mjablecnik** [comment]
My opinion is that developer should not be overwhelmed by many small packages and options on start of project when cannot. Some other third-party packages could exists of course but for some bigger issues where may exists more different ways. For example: ORM, Swagger docs generation, Auth, etc..

I do not have any problem to turn this issue into a proposal talk.. :)

**Comment by francescovallone** [comment]
After some consideration I'm thinking of move serinus_cors and serinus_rate_limiter in the core package while leaving serinus_config and serinus_serve_static out for now. Serinus Config will probably receive some changes to reflect the possibility to use multiple readers instead of dotenv files only. I'm leaving the proposal open for now for future discussion regarding these other two packages.
